const express = require("express")
const cors = require("cors")
const helmet = require("helmet")
const sequelize = require('./database')
const path = require("path")
const category = require("./routes/Pillar Pole/StockRouts/Category")
const Products = require("./routes/Pillar Pole/StockRouts/Product")
const Purchase = require("./routes/Pillar Pole/StockRouts/Purchase")
const PStocksOpeningBal = require("./routes/Pillar Pole/StockRouts/StockOpeningBal")
const StockTransfer = require("./routes/Pillar Pole/StockRouts/StockTransfer")
const PStockReturn = require("./routes/Pillar Pole/StockRouts/StockReturn")
const PStockUsed = require("./routes/Pillar Pole/StockRouts/StockUsed")
const NewProduction = require("./routes/Pillar Pole/ProductionStock/NewProduction")
const Operators = require("./routes/Pillar Pole/ProductionStock/Operators")
const Machines = require("./routes/Pillar Pole/ProductionStock/Machine")
const Customer = require("./routes/Pillar Pole/CustomerRouts/NewCustomer")
const Cutting = require("./routes/Pillar Pole/ProductionStock/Cutting")
const Printing = require("./routes/Pillar Pole/ProductionStock/Printing")
const Recycle=require("./routes/Pillar Pole/ProductionStock/Recycle")
const Supplier = require("./routes/Pillar Pole/SupplierRoutes/NewSupplier")
const Sales = require("./routes/Pillar Pole/SalesRouts/Sales")
const WayBill = require("./routes/Pillar Pole/CustomerRouts/WayBill")
const Refund = require("./routes/Pillar Pole/CustomerRouts/Refund")
const ExpaenseAccount =require("./routes/Pillar Pole/AccountRouts/ExpenseAccount")
const SalesRep =require("./routes/Pillar Pole/AccountRouts/SalesRep")
const Company =require("./routes/Pillar Pole/AccountRouts/Company")
const PostBill =require("./routes/Pillar Pole/AccountRouts/PostBills")
const BankDepositeTransfer =require("./routes/Pillar Pole/AccountRouts/BankDepositTransfer")
const BankOpeningBal =require("./routes/Pillar Pole/AccountRouts/BankopeningBal")
const AccountType =require("./routes/Pillar Pole/AccountRouts/AccountType")
const Acheads =require("./routes/Pillar Pole/AccountRouts/AcHeads")
const AccountChart =require("./routes/Pillar Pole/AccountRouts/AccountChart")
const SupplierReport =require("./routes/Pillar Pole/SupplierRoutes/SupplierReport")
const PaymentVocher =require("./routes/Pillar Pole/AccountRouts/Payment")
const PillarOpenCloseBal =require("./routes/Pillar Pole/StockRouts/ProductOpenCloseBal")

// justice Apis
const JusticeCatory =require("./routes/JusticePapperMill/StockRoutes/Category")
const JusticeProducts = require("./routes/JusticePapperMill/StockRoutes/Products")
const PurchaseStocks = require("./routes/JusticePapperMill/StockRoutes/PurchaseStocks")
const StocksProduction = require("./routes/JusticePapperMill/StockRoutes/StockProduction")
const StocksOpeningBal = require("./routes/JusticePapperMill/StockRoutes/StockOpeningBal")
const JusticeStocksTransfer = require("./routes/JusticePapperMill/StockRoutes/StockTransfer")
const JStockused = require("./routes/JusticePapperMill/StockRoutes/StockUsed")
const JNewSupplier = require("./routes/JusticePapperMill/SuppliersRoutes/NewSuppliers")
const JSupplierReport = require("./routes/JusticePapperMill/SuppliersRoutes/SupplierReport")
const JMakeSales = require("./routes/JusticePapperMill/SalesRoutes/MakeSales")
const JNewCustomers = require("./routes/JusticePapperMill/CustomerRoutes/NewCustomers")
const Jrecptvocher = require("./routes/JusticePapperMill/SalesRoutes/ReciptVocher")
const JDriverReg = require("./routes/JusticePapperMill/SalesRoutes/DriverReg")
const JWayBill = require("./routes/JusticePapperMill/SalesRoutes/WayBill")
const JSalesRep = require("./routes/JusticePapperMill/CustomerRoutes/SalesRep")
const JRefund = require("./routes/JusticePapperMill/CustomerRoutes/Refund")
const JPostBill = require("./routes/JusticePapperMill/AccountRoutes/PostBills")
const JCompany = require("./routes/JusticePapperMill/AccountRoutes/Company")
const JExpenseAccount = require("./routes/JusticePapperMill/AccountRoutes/ExpenseAccount")
const JPaymentVocher = require("./routes/JusticePapperMill/AccountRoutes/PaymentVocher")
const JBankDepositTransfers = require("./routes/JusticePapperMill/AccountRoutes/BankDepositTransfer")
const JOpeningBal = require("./routes/JusticePapperMill/AccountRoutes/BankOpeningClosing")
const JAcheads = require("./routes/JusticePapperMill/AccountRoutes/AcHeads")
const Jacchart = require("./routes/JusticePapperMill/AccountRoutes/AccountChart")
const JaccountType = require("./routes/JusticePapperMill/AccountRoutes/AccountType")
const JDeleteItems = require("./routes/JusticePapperMill/DeleteRoutes/DeleteItems")
const JStockReturn = require("./routes/JusticePapperMill/StockRoutes/StockReturn")
const JCashFlow = require("./routes/JusticePapperMill/AccountRoutes/CashFlow")



// Efficient Apis
const ENewProducts = require("./routes/EfficientLPG/ProductsRoutes/NewProducts")
const EPumps = require("./routes/EfficientLPG/ProductsRoutes/Pump")
const EStockRecieveds = require("./routes/EfficientLPG/ProductsRoutes/StockRecieved")
const EReturnProducts = require("./routes/EfficientLPG/ProductsRoutes/ReturnProducts")
const ENewCustomers= require("./routes/EfficientLPG/CustomersRoutes/NewCustomer")
const EProductTransfer= require("./routes/EfficientLPG/ProductsRoutes/ProductTransfer")
const ENewSupplier= require("./routes/EfficientLPG/SupplierRoutes/NewSupplier")
const EAccountReport= require("./routes/EfficientLPG/SupplierRoutes/AccountReport")
const EsalesEntry= require("./routes/EfficientLPG/SalesRoutes/SalesEntry")
const EPumpAttendants= require("./routes/EfficientLPG/SalesRoutes/PumpAttendants")
const ESalesEntryCredit= require("./routes/EfficientLPG/SalesRoutes/SalesEntryCredit")
const ERefund= require("./routes/EfficientLPG/CustomersRoutes/Refund")
const ECusDeposit= require("./routes/EfficientLPG/CustomersRoutes/Deposit")
const EfficientExpaenseAccount =require("./routes/EfficientLPG/AccountRoutes/AccountChart")
const EfficientPaymentVocher =require("./routes/EfficientLPG/AccountRoutes/PaymentVocher")
const EfficientBankDepositTransfers =require("./routes/EfficientLPG/AccountRoutes/BankDepositTransfers")
const EfficientBankOpeningBal =require("./routes/EfficientLPG/AccountRoutes/BankOpeningBal")



// Daily FUnctions Runs
const cron = require('node-cron');
const {SetAllOpeningQuantities}  =require("./controllers/Pillar Pole/StockControllers/StockOpenCloseBal")


require("dotenv").config()
app = express()

app.use(express.urlencoded({ extended: false }));
app.use(cors())
// app.use(helmet())
app.use(express.json())
app.use(express.static("public"))


app.use("/api",category)
app.use("/api",Products)
app.use("/api",Purchase)
app.use("/api",PStocksOpeningBal)
app.use("/api",StockTransfer)
app.use("/api",NewProduction)
app.use("/api",Operators)
app.use("/api",Machines)
app.use("/api",Customer)
app.use("/api",Cutting)
app.use("/api",Printing)
app.use("/api",Recycle)
app.use("/api",Supplier)
app.use("/api",PStockUsed) 
app.use("/api",SupplierReport)
app.use("/api",Sales)
app.use("/api",WayBill)
app.use("/api",Refund)
app.use("/api",ExpaenseAccount)
app.use("/api",SalesRep)
app.use("/api",Company)
app.use("/api",PostBill)
app.use("/api",BankDepositeTransfer)
app.use("/api",BankOpeningBal)
app.use("/api",AccountType)
app.use("/api",Acheads)
app.use("/api",AccountChart)
app.use("/api",PaymentVocher)
app.use("/api",PStockReturn)
app.use("/api",PillarOpenCloseBal)

// Justices Apis
app.use("/api",JusticeCatory)
 app.use("/api",JusticeProducts)
 app.use("/api",PurchaseStocks)
 app.use("/api",StocksProduction)
 app.use("/api",StocksOpeningBal)
 app.use("/api",JusticeStocksTransfer)
 app.use("/api",JStockused)
 app.use("/api",JNewSupplier)
 app.use("/api",JSupplierReport)
 app.use("/api",JMakeSales)
 app.use("/api",JNewCustomers)
 app.use("/api",Jrecptvocher)
 app.use("/api",JDriverReg)
 app.use("/api",JWayBill)
app.use("/api", JSalesRep)
app.use("/api", JRefund)
app.use("/api", JPostBill)
app.use("/api", JCompany)
app.use("/api", JExpenseAccount)
app.use("/api", JPaymentVocher)
app.use("/api", JBankDepositTransfers)
app.use("/api", JOpeningBal)
app.use("/api", JAcheads)
app.use("/api", Jacchart)
app.use("/api", JaccountType)
app.use("/api", JDeleteItems)
app.use("/api", JStockReturn)
app.use("/api", JCashFlow)

// Efficient Apis
app.use("/api",ENewProducts)
app.use("/api",EPumps)
app.use("/api",EStockRecieveds)
app.use("/api",EReturnProducts)
app.use("/api",ENewCustomers)
app.use("/api",EProductTransfer)
app.use("/api",ENewSupplier)
app.use("/api",EAccountReport)
app.use("/api",EsalesEntry)
app.use("/api",EPumpAttendants)
app.use("/api",ESalesEntryCredit)
app.use("/api",ERefund)
app.use("/api",ECusDeposit)
app.use("/api",EfficientExpaenseAccount)
app.use("/api",EfficientPaymentVocher)
app.use("/api",EfficientBankDepositTransfers)
app.use("/api",EfficientBankOpeningBal)

 
 
// // Daily FUnctions
cron.schedule('0 0 6,19 * * *', SetAllOpeningQuantities, {
    timezone: "Africa/Lagos"
});
// cron.schedule('*/2 * * * * *', SetAllOpeningQuantities, {
//     timezone: "Africa/Lagos"
// });


sequelize.sync().then(()=>{
    app.listen(process.env.PORT,(req,res)=>{
        console.log(`Listening at port ${process.env.PORT}`)
    })
})
